# Generated by Django 5.0.7 on 2024-08-01 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
    ]
