# Generated by Django 5.0.7 on 2024-08-02 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='review',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.genre'),
        ),
        migrations.AddField(
            model_name='review',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.industry'),
        ),
        migrations.AlterField(
            model_name='review',
            name='streaming_platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.streamingplatform'),
        ),
    ]
